project_name: YAMLQuest

builds:
  - main: ./main.go
    goos:
      - linux
    goarch:
      - amd64
    binary: yquest

archives:
  - format: tar.gz
    files:
      - yquest

# snapshot:
#   enabled: true

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"

release:
  disable: true  # disables pushing a GitHub release during testing
